# Generated by Django 5.2.6 on 2026-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('code', models.TextField(blank=True)),
                ('passed', models.BooleanField(default=False)),
                ('tests_passed', models.PositiveIntegerField(default=0)),
                ('tests_total', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('quiz_correct', models.PositiveIntegerField(blank=True, null=True)),
                ('quiz_total', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
