# Generated by Django 5.2.6 on 2026-09-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_xpevent_exerciseprogress_solution_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.SlugField()),
                ('role', models.CharField(choices=[('user', 'Learner'), ('assistant', 'Tutor')], max_length=10)),
                ('content', models.TextField()),
                ('display', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
