# Generated by Django 5.2.6 on 2026-09-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_tutormessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
