# Generated by Django 5.2.6 on 2026-10-09 09:42

import django.db.models.deletion
import learn.models
from django.conf import settings
from django.db import migrations, models


OWNED_MODELS = ['ExerciseProgress', 'XPEvent', 'TutorMessage', 'NotebookEntry']


def give_existing_progress_to_owner(apps, schema_editor):
    """Before accounts, the site had one learner. Their progress goes to the site owner:
    the first superuser, else the first staff account, else the first account.
    With no accounts at all, an "owner" account is made (set its password with
    `python manage.py changepassword owner`)."""
    models = [apps.get_model('learn', name) for name in OWNED_MODELS]
    if not any(m.objects.filter(user__isnull=True).exists() for m in models):
        return
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    owner = (User.objects.filter(is_superuser=True).order_by('id').first()
             or User.objects.filter(is_staff=True).order_by('id').first()
             or User.objects.order_by('id').first())
    if owner is None:
        owner = User.objects.create(username='owner', password='!', is_staff=True, is_superuser=True)
    for model in models:
        model.objects.filter(user__isnull=True).update(user=owner)


def owner_field():
    return models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0004_notebookentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default=learn.models.new_invite_code, max_length=40, unique=True)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text='Who it is for, e.g. "Cohort 1".',
                        max_length=120,
                    ),
                ),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("uses", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LearningEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("run", "Ran the tests"),
                            ("test_run", "Ran one test"),
                            ("selection_run", "Ran selected code"),
                            ("passed", "Passed an exercise"),
                            ("quiz", "Took a quiz"),
                            ("hint", "Asked the tutor"),
                            ("solution_viewed", "Opened the solution"),
                            ("lesson_finished", "Finished a lesson"),
                            ("chapter_skipped", "Skipped a chapter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                ("seconds_spent", models.PositiveIntegerField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="exerciseprogress",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notebookentry",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tutormessage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="xpevent",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="exerciseprogress",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="notebookentry",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="xpevent",
            name="key",
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name="exerciseprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "slug"), name="unique_progress_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="notebookentry",
            constraint=models.UniqueConstraint(
                fields=("user", "slug"), name="unique_notebook_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="xpevent",
            constraint=models.UniqueConstraint(
                fields=("user", "key"), name="unique_xp_key_per_user"
            ),
        ),
        migrations.AddField(
            model_name="learningevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="learningevent",
            index=models.Index(
                fields=["user", "created_at"], name="learn_learn_user_id_23857f_idx"
            ),
        ),
        migrations.RunPython(give_existing_progress_to_owner, migrations.RunPython.noop),
        migrations.AlterField(model_name='exerciseprogress', name='user', field=owner_field()),
        migrations.AlterField(model_name='notebookentry', name='user', field=owner_field()),
        migrations.AlterField(model_name='tutormessage', name='user', field=owner_field()),
        migrations.AlterField(model_name='xpevent', name='user', field=owner_field()),
    ]
