# Generated by Django 5.2.6 on 2026-10-09 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0005_accounts_and_activity_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("hours", models.PositiveSmallIntegerField(default=0)),
                ("language", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Path",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("job", "Job path"), ("skill", "Skill path")],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("level", models.CharField(blank=True, max_length=20)),
                ("hours", models.PositiveSmallIntegerField(default=0)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("project", models.JSONField(blank=True, default=dict)),
                ("capstone", models.JSONField(blank=True, default=dict)),
                ("placement_test", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["kind", "order", "id"],
            },
        ),
        migrations.AlterField(
            model_name="learningevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("run", "Ran the tests"),
                    ("test_run", "Ran one test"),
                    ("selection_run", "Ran selected code"),
                    ("passed", "Passed an exercise"),
                    ("quiz", "Took a quiz"),
                    ("hint", "Asked the tutor"),
                    ("solution_viewed", "Opened the solution"),
                    ("lesson_finished", "Finished a lesson"),
                    ("chapter_skipped", "Skipped a chapter"),
                    ("path_skipped", "Skipped a prerequisite"),
                    ("path_chosen", "Chose a job path"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("learning_goal", models.TextField(blank=True)),
                ("exercise_idea", models.TextField(blank=True)),
                ("exercises", models.JSONField(blank=True, default=list)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="learn.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="learn.path",
            ),
        ),
        migrations.CreateModel(
            name="PathChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="learn.path",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PathStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("prerequisite", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="learn.path",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_jobs",
                        to="learn.path",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SkippedPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="learn.path",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "path"), name="unique_skip_per_user"
                    )
                ],
            },
        ),
    ]
