# Generated by Django 5.2.6 on 2026-10-09 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0006_catalog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="content",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="path",
            name="ai_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="path",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="path",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_paths",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="path",
            name="request",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="learningevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("run", "Ran the tests"),
                    ("test_run", "Ran one test"),
                    ("selection_run", "Ran selected code"),
                    ("passed", "Passed an exercise"),
                    ("quiz", "Took a quiz"),
                    ("hint", "Asked the tutor"),
                    ("solution_viewed", "Opened the solution"),
                    ("lesson_finished", "Finished a lesson"),
                    ("chapter_skipped", "Skipped a chapter"),
                    ("path_skipped", "Skipped a prerequisite"),
                    ("path_chosen", "Chose a job path"),
                    ("placement", "Took a placement test"),
                    ("path_generated", "Generated a skill path"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PlacementAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
                ("tasks_passed", models.PositiveIntegerField(default=0)),
                ("tasks_total", models.PositiveIntegerField(default=0)),
                ("passed", models.BooleanField(default=False)),
                ("skipped_chapters", models.JSONField(blank=True, default=list)),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="learn.path",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ChapterProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz_correct", models.PositiveIntegerField(default=0)),
                ("quiz_total", models.PositiveIntegerField(default=0)),
                ("done", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="learn.chapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "chapter"),
                        name="unique_chapter_progress_per_user",
                    )
                ],
            },
        ),
    ]
