# Generated by Django 5.2.6 on 2026-10-10 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0007_placement_and_generated_paths"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("run", "Ran the tests"),
                    ("test_run", "Ran one test"),
                    ("selection_run", "Ran selected code"),
                    ("passed", "Passed an exercise"),
                    ("quiz", "Took a quiz"),
                    ("hint", "Asked the tutor"),
                    ("solution_viewed", "Opened the solution"),
                    ("lesson_finished", "Finished a lesson"),
                    ("chapter_skipped", "Skipped a chapter"),
                    ("path_skipped", "Skipped a prerequisite"),
                    ("path_chosen", "Chose a job path"),
                    ("placement", "Took a placement test"),
                    ("path_generated", "Generated a skill path"),
                    ("cards_added", "Added flashcards"),
                    ("card_reviewed", "Reviewed a flashcard"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("front", models.TextField()),
                ("code", models.TextField(blank=True)),
                ("back", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[("ai", "Written by AI"), ("quiz", "From the quiz")],
                        default="ai",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to="learn.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter", "order"],
            },
        ),
        migrations.CreateModel(
            name="CardReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("box", models.PositiveSmallIntegerField(default=0)),
                ("due_at", models.DateTimeField()),
                ("reviews", models.PositiveIntegerField(default=0)),
                ("lapses", models.PositiveIntegerField(default=0)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="learn.flashcard",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["user", "due_at"], name="learn_cardr_user_id_f07e66_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "card"), name="one_review_per_card"
                    )
                ],
            },
        ),
    ]
