# Generated by Django 5.2.6 on 2026-10-10 08:09

from django.db import migrations, models


def drop_old_ai_decks(apps, schema_editor):
    # Decks written before cards became hands-on are rewritten the next time someone adds the chapter.
    apps.get_model('learn', 'Flashcard').objects.filter(source='ai').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0008_flashcards"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="expected",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="kind",
            field=models.CharField(
                choices=[
                    ("output", "Predict the output"),
                    ("complete", "Complete the code"),
                    ("concept", "Key concept"),
                ],
                default="concept",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="language",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="solution",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(drop_old_ai_decks, migrations.RunPython.noop),
    ]
