# Generated by Django 5.2.6 on 2026-10-10 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0009_hands_on_flashcards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("run", "Ran the tests"),
                    ("test_run", "Ran one test"),
                    ("selection_run", "Ran selected code"),
                    ("passed", "Passed an exercise"),
                    ("quiz", "Took a quiz"),
                    ("hint", "Asked the tutor"),
                    ("solution_viewed", "Opened the solution"),
                    ("lesson_finished", "Finished a lesson"),
                    ("chapter_skipped", "Skipped a chapter"),
                    ("path_skipped", "Skipped a prerequisite"),
                    ("path_chosen", "Chose a job path"),
                    ("placement", "Took a placement test"),
                    ("path_generated", "Generated a skill path"),
                    ("cards_added", "Added flashcards"),
                    ("card_reviewed", "Reviewed a flashcard"),
                    ("project_srs", "Set up their own project"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("described", "Described"),
                            ("uploaded", "Uploaded SRS"),
                        ],
                        max_length=10,
                    ),
                ),
                ("brief", models.JSONField(blank=True, default=dict)),
                ("srs", models.JSONField(default=dict)),
                ("done", models.JSONField(blank=True, default=list)),
                ("language", models.CharField(default="en", max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
